Repository voiceflow/general-runtime, pull requests merged in 2021-11, with the labels that each got.

#214 feat: goto (VF-2144)
  lib/services/runtime/handlers/interaction.ts
  package.json
  tests/lib/services/runtime/handlers/interaction.unit.ts
  yarn.lock
Labels: in progress

#215 feat: Set user_id to UserId for state api calls (VF-2153)
  lib/services/interact.ts
  lib/services/runtime/index.ts
  lib/services/runtime/types.ts
  runtime/lib/Context/types.ts
  tests/lib/services/interact.unit.ts
  tests/lib/services/runtime/index.unit.ts
Labels: ready for review, dont merge

#217 fix(deps): bump orb version (VF-000)
  .circleci/config.yml
Labels: ready for review

#218 feat: reduce immer use (VF-000)
  runtime/lib/Runtime/Store/index.ts
  runtime/lib/Runtime/utils/variables.ts
Labels: ready for review

#223 ci: e2e manual approval
  .circleci/config.yml
Labels: ready for review

#224 feat: base program version id (VF-000)
  runtime/lib/Runtime/Stack/index.ts
  runtime/lib/Runtime/cycleStack.ts
  runtime/lib/Runtime/index.ts
  tests/runtime/lib/Runtime/cycleStack.unit.ts
  tests/runtime/lib/Runtime/index.unit.ts
Labels: ready for review

#225 fix: fix base flow logic (VF-000)
  lib/services/runtime/init.ts
  runtime/lib/Runtime/cycleStack.ts
  runtime/lib/Runtime/index.ts
  tests/lib/services/runtime/init.unit.ts
  tests/runtime/lib/Runtime/cycleStack.unit.ts
Labels: ready for review

#228 feat: new action system (VF-000)
  lib/services/dialog/utils.ts
  lib/services/runtime/handlers/_v1.ts
  lib/services/runtime/handlers/capture.ts
  lib/services/runtime/handlers/command.ts
  lib/services/runtime/handlers/interaction.ts
  lib/services/runtime/handlers/state/oneShot.ts
  lib/services/runtime/handlers/state/preliminary.ts
  lib/services/runtime/handlers/state/stream.ts
  runtime/lib/Runtime/cycleHandler.ts
  runtime/lib/Runtime/index.ts
  tests/lib/services/dialog/utils.unit.ts
  tests/lib/services/runtime/handlers/_v1.unit.ts
  tests/lib/services/runtime/handlers/capture.unit.ts
  tests/lib/services/runtime/handlers/command.unit.ts
  tests/lib/services/runtime/handlers/interaction.unit.ts
  tests/lib/services/runtime/handlers/state/preliminary.unit.ts
  tests/lib/services/runtime/handlers/state/stream.unit.ts
  tests/runtime/lib/Runtime/cycleHandler.unit.ts
  tests/runtime/lib/Runtime/index.unit.ts
Labels: ready for review

#227 feat: no-reply/no-match improvements (VF-1997)
  lib/clients/remoteDataAPI.ts
  lib/services/dialog/index.ts
  lib/services/dialog/synonym.ts
  lib/services/dialog/utils.ts
  lib/services/nlu/index.ts
  lib/services/nlu/nlc.ts
  lib/services/runtime/handlers/capture.ts
  lib/services/runtime/handlers/interaction.ts
  lib/services/runtime/handlers/noMatch.ts
  lib/services/runtime/handlers/noReply.ts
  lib/services/runtime/handlers/state/preliminary.ts
  lib/services/runtime/index.ts
  lib/services/runtime/types.ts
  lib/services/runtime/utils.ts
  lib/services/state/index.ts
  package.json
  runtime/lib/DataAPI/creatorDataAPI.ts
  runtime/lib/DataAPI/localDataAPI.ts
  runtime/lib/DataAPI/serverDataAPI.ts
  runtime/lib/DataAPI/types.ts
  runtime/lib/Handler/index.ts
  runtime/lib/Handlers/next.ts
  runtime/lib/Handlers/reset.ts
  runtime/lib/Lifecycle/types.ts
  runtime/lib/Program/index.ts
  runtime/lib/Runtime/Stack/Frame/index.ts
  runtime/lib/Util/index.ts
  tests/lib/services/dialog/utils.unit.ts
  tests/lib/services/runtime/handlers/capture.unit.ts
  tests/lib/services/runtime/handlers/interaction.unit.ts
  tests/lib/services/runtime/handlers/noMatch.unit.ts
  tests/lib/services/runtime/handlers/noMath.unit.ts
  tests/lib/services/runtime/handlers/noReply.unit.ts
  tests/lib/services/runtime/utils.unit.ts
  yarn.lock
Labels: ready for review
