Repository voiceflow/general-runtime, pull requests merged in 2021-08, with the labels that each got.

#148 docs: fix Node.js example (VF-000)
  backend/docs/openapi.yaml
Labels: ready for review

#149 feat: add `last_utterance` global variable (VF-1162)
  lib/services/runtime/index.ts
  lib/services/runtime/types.ts
  tests/lib/services/runtime/index.unit.ts
Labels: ready to merge

#150 fix: filters buttons with empty name (VF-1226)
  lib/services/runtime/utils.ts
Labels: autorebase:opt-in

#155 fix: google sheets val to num (VF-1169)
  runtime/lib/Handlers/integrations/utils.ts
Labels: ready to merge

#156 docs: update examples (VF-1422)
  backend/docs/openapi.yaml
Labels: ready for review

#157 feat: text trace (VF-1362)
  lib/services/runtime/handlers/index.ts
  lib/services/runtime/handlers/text.ts
  package.json
  yarn.lock
Labels: in progress

#161 feat: better support for big JSON (VF-1399)
  backend/constants.ts
  backend/expressMiddleware.ts
  config.ts
  lib/services/runtime/index.ts
  types.ts
Labels: ready for review, autorebase:opt-in

#162 fix: loosen response timeout from 10s to 30s (VF-1399)
  config.ts
Labels: ready to merge

#164 fix: set default timeout time to 10s (VF-1549)
  config.ts
Labels: ready for review

#165 fix: cleanup logs (VF-1476)
  backend/expressMiddleware.ts
  lib/clients/analytics.ts
  lib/services/dialog/index.ts
  lib/services/nlu/nlc.ts
  lib/services/runtime/handlers/text.ts
  lib/services/runtime/index.ts
  lib/services/state/index.ts
  lib/services/tts/index.ts
  lib/utils.ts
  package.json
  server.ts
  start.ts
  yarn.lock
Labels: ready for review, autorebase:opt-in

#167 fix: dm analytics (VF-1593)
  lib/services/analytics.ts
  lib/services/index.ts
  lib/services/interact.ts
  lib/services/runtime/index.ts
  tests/lib/services/analytics.unit.ts
  tests/lib/services/interact.unit.ts
Labels: ready to merge

#168 feat: text prompts (VF-000)
  .eslintignore
  app.config.js
  lib/middlewares/rateLimit.ts
  lib/services/dialog/index.ts
  lib/services/dialog/utils.ts
  lib/services/runtime/handlers/capture.ts
  lib/services/runtime/handlers/interaction.ts
  lib/services/runtime/handlers/noMatch.ts
  lib/services/runtime/handlers/repeat.ts
  lib/services/runtime/handlers/speak.ts
  lib/services/runtime/handlers/state/stream.ts
  lib/services/runtime/handlers/text.ts
  lib/services/runtime/init.ts
  lib/services/runtime/types.ts
  lib/services/runtime/utils.ts
  lib/services/session/mongo.ts
  lib/services/utils.ts
  lib/utils.ts
  package.json
  runtime/lib/Handlers/code/index.ts
  runtime/lib/Handlers/code/utils.ts
  runtime/lib/Handlers/integrations/utils.ts
  runtime/lib/Lifecycle/index.ts
  tests/lib/services/runtime/handlers/noMath.unit.ts
  tests/lib/services/runtime/handlers/repeat.unit.ts
  tests/lib/services/runtime/handlers/speak.unit.ts
  tests/lib/services/runtime/handlers/state/stream.unit.ts
  tests/lib/services/runtime/handlers/text.unit.ts
  tests/lib/services/runtime/init.unit.ts
  tests/lib/services/runtime/utils.unit.ts
  tests/runtime/lib/DataAPI/serverDataAPI.unit.ts
  tests/runtime/lib/Runtime/Trace/index.unit.ts
  tests/runtime/lib/Runtime/utils/programManager.unit.ts
  tsconfig.json
  types.ts
  yarn.lock
Labels: ready to merge
