Repository voiceflow/general-runtime, pull requests merged in 2021-01, with the labels that each got.

#11 feat: nlu
  .env.test
  config.ts
  lib/clients/remoteDataAPI.ts
  lib/controllers/interact.ts
  lib/services/nlu/index.ts
  lib/services/runtime/handlers/capture.ts
  lib/services/runtime/handlers/command.ts
  lib/services/runtime/handlers/event/index.ts
  lib/services/runtime/handlers/interaction.ts
  lib/services/runtime/handlers/repeat.ts
  lib/services/runtime/handlers/state/stream.ts
  lib/services/runtime/index.ts
  lib/services/runtime/types.ts
  lib/services/runtime/utils.ts
  lib/services/state/index.ts
  package.json
  tests/lib/services/nlu/index.unit.ts
  tests/lib/services/runtime/index.unit.ts
  types.ts
  yarn.lock
Labels: in progress

#13 feat: tts working
  lib/controllers/interact.ts
  lib/services/nlu/index.ts
  lib/services/runtime/index.ts
  lib/services/runtime/init.ts
  lib/services/runtime/types.ts
  lib/services/state/index.ts
  lib/services/tts/index.ts
  logger.ts
  package.json
  tests/lib/controllers/interact.unit.ts
  tests/lib/services/tts/index.unit.ts
  types.ts
  yarn.lock
Labels: ready to merge

#15 feat: dialog management
  .vscode/launch.json
  lib/services/dialog/index.ts
  lib/services/dialog/utils.ts
  package.json
  tests/lib/services/dialog/fixture.ts
  tests/lib/services/dialog/index.unit.ts
  tests/lib/services/dialog/utils.unit.ts
  tsconfig.json
  yarn.lock
Labels: ready for review

#16 feat: chips
  lib/controllers/interact.ts
  lib/services/chips/index.ts
  lib/services/chips/utils.ts
  lib/services/dialog/index.ts
  lib/services/dialog/utils.ts
  lib/services/index.ts
  lib/services/runtime/handlers/interaction.ts
  package.json
  tests/lib/controllers/interact.unit.ts
  tests/lib/services/dialog/fixture.ts
  tests/lib/services/dialog/index.unit.ts
  yarn.lock
Labels: in review

#19 feat: cached data
  lib/clients/index.ts
  lib/controllers/interact.ts
  lib/services/chips/index.ts
  lib/services/dialog/index.ts
  lib/services/nlu/index.ts
  lib/services/runtime/index.ts
  lib/services/state/cacheDataAPI.ts
  lib/services/state/index.ts
  package.json
  tests/lib/services/dialog/fixture.ts
  tests/lib/services/dialog/index.unit.ts
  tests/lib/services/nlu/index.unit.ts
  tests/lib/services/runtime/index.unit.ts
  tests/lib/services/state/index.unit.ts
  types.ts
  yarn.lock
Labels: ready for review

#21 fix: bump @voiceflow/backend-utils
  package.json
  yarn.lock
Labels: ready for review

#22 fix: allow dm prompts
  lib/services/dialog/index.ts
  lib/services/dialog/utils.ts
  package.json
  yarn.lock
Labels: in review

#25 fix: stream handler
  lib/services/runtime/init.ts
Labels: ready to merge

#26 fix: built in nlc intents
  lib/services/dialog/index.ts
  lib/services/nlu/index.ts
  lib/services/nlu/nlc.ts
Labels: ready to merge

#29 feat: creator-api
  .env.test
  config.ts
  lib/clients/dataAPI.ts
  lib/clients/index.ts
  package.json
  tests/lib/clients/dataAPI.unit.ts
  types.ts
  yarn.lock
Labels: ready for review

#28 docs: context handlers
  README.md
  documentation/asr.md
  documentation/chips.md
  documentation/dialog.md
  documentation/nlu.md
  documentation/runtime.md
  documentation/tts.md
  lib/services/asr/index.ts
  lib/services/chips/index.ts
  lib/services/dialog/index.ts
  lib/services/nlu/index.ts
  lib/services/runtime/index.ts
  lib/services/tts/index.ts
  typedoc.js
Labels: in progress
