Repository voiceflow/general-runtime, pull requests merged in 2021-02, with the labels that each got.

#57 chore(deps): remove crypto dependency
  .depcheckrc
  package.json
  yarn.lock
Labels: ready for review

#59 fix: nested replace (CORE-000)
  lib/services/runtime/handlers/speak.ts
Labels: ready to merge

#52 feat: add visual handler (CORE-4884)
  lib/services/runtime/handlers/index.ts
  lib/services/runtime/handlers/visual.ts
  logger.ts
  package.json
  tests/lib/services/runtime/handlers/visual.unit.ts
  yarn.lock
Labels: env-eloquent-khayyam, ready to merge

#53 feat: only add tts handler if specified in config (CORE-4944)
  lib/controllers/interact.ts
  package.json
  tests/lib/controllers/interact.unit.ts
  yarn.lock
Labels: ready to merge

#58 feat: add intent confidence to debug message (CORE-5004)
  lib/services/nlu/index.ts
  lib/services/runtime/handlers/capture.ts
  lib/services/runtime/index.ts
  lib/services/runtime/utils.ts
  tests/lib/services/runtime/handlers/capture.unit.ts
  tests/lib/services/runtime/handlers/interaction.unit.ts
  tests/lib/services/runtime/index.unit.ts
Labels: ready for review

#62 fix: stop number slot from being filled with entire utterances (CORE-5164)
  lib/services/dialog/index.ts
Labels: ready to merge

#63 fix: account for empty stack (CORE-000)
  lib/services/state/index.ts
Labels: ready for review

#64 feat: one shot intent handler (CORE-000)
  lib/services/runtime/handlers/state/index.ts
  lib/services/runtime/handlers/state/oneShot.ts
Labels: ready for review

#65 feat: API Key Verification (CORE-5221)
  .env.test
  config.ts
  lib/clients/dataAPI.ts
  lib/clients/index.ts
  lib/controllers/interact.ts
  lib/services/runtime/index.ts
  lib/services/state/index.ts
  package.json
  tests/lib/clients/dataAPI.unit.ts
  tests/lib/controllers/interact.unit.ts
  tests/lib/services/runtime/index.unit.ts
  tests/lib/services/state/index.unit.ts
  types.ts
  yarn.lock
Labels: dont merge, in review

#66 feat: rate limiting (CORE-5291)
  .env.test
  backend/api/routers/interact.ts
  config.ts
  lib/clients/index.ts
  lib/clients/rateLimiter.ts
  lib/clients/redis.ts
  lib/middlewares/index.ts
  lib/middlewares/rateLimit.ts
  lib/services/index.ts
  lib/services/rateLimit.ts
  package.json
  tests/lib/clients/rateLimiter.unit.ts
  tests/lib/middlewares/rateLimit.unit.ts
  tests/lib/services/rateLimit.unit.ts
  tests/server/interact.unit.ts
  types.ts
  typings/voiceflow__verror.d.ts
  yarn.lock
Labels: dont merge

#68 fix: remove origin requirement (CORE-000)
  lib/clients/dataAPI.ts
  lib/controllers/interact.ts
  lib/services/state/index.ts
  tests/lib/clients/dataAPI.unit.ts
Labels: ready for review

#60 feat: implement NATO/APCO slot types (CORE-4839)
  lib/controllers/interact.ts
  lib/middlewares/rateLimit.ts
  lib/services/dialog/index.ts
  lib/services/index.ts
  lib/services/runtime/handlers/noMatch.ts
  lib/services/runtime/handlers/speak.ts
  lib/services/runtime/init.ts
  lib/services/slots/index.ts
  lib/services/tts/index.ts
  package.json
  tests/lib/controllers/interact.unit.ts
  tests/lib/services/dialog/index.unit.ts
  tests/lib/services/slots/index.unit.ts
  yarn.lock
Labels: ready for review
